### ISSUE TITLE
Handle pseudo classes like :hover

### ISSUE THREAD

**Issue by TheJaredWilcurt** [red-perfume/red-perfume#15]
Probably something like this:
```css
.cow {
  background: #F00;
  color: #00F;
}
.cow:hover {
  background: #0F0;
}
```
```css
.rp__background__--COLON__--OCTOTHORPF00 { background: #F00 }
.rp__color__--COLON__--OCTOTHORP00F { color: #00F }
.rp__background__--COLON__--OCTOTHORP0F0___-HOVER:hover { background: #0F0 }
```
```css
.rp__a { background: #F00 }
.rp__b { color: #00F }
.rp__c:hover { background: #0F0 }
```

Should probably support all pseudo classes:

* https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes
