### ISSUE TITLE
Handle pseudo elements like :before

### ISSUE THREAD

**Issue by TheJaredWilcurt** [red-perfume/red-perfume#16]
Probably something like this:
```css
.cow {
    padding: 10px;
}
.cow:before {
    content: '';
    background: #F00;
}
```
```css
.rp__padding__--COLON10px { padding: 10px }
.rp__content__--COLON__--SINGLEQUOTE__--SINGLEQUOTE___--BEFORE:before { content: '' }
.rp__background__--COLON__--OCTOTHORPF00___--BEFORE:before { background: #F00 }
```
```css
.rp__a { padding: 10px }
.rp__b:before { content: '' }
.rp__c:before { background: #F00 }
```

Should support all pseudo elements

* https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-elements
