### ISSUE TITLE
Handle nested selectors

### ISSUE THREAD

**Issue by TheJaredWilcurt** [red-perfume/red-perfume#17]
Probably something like this:
```css
/* input */
.cow {
    display: block;
    padding: 10px;
}
.cow .moo {
    margin: 4px;
}
```
```css
/* verbose output */
.rp__display__--COLONblock { display: block }
.rp__padding__--COLON10px { padding: 10px }
.rp__margin__--COLON4px_---PARENT1 .rp__margin__--COLON4px_---CHILD { margin: 4px }
```
```css
/* uglified output */
.rp__a { display: block }
.rp__b { padding: 10px }
.rp__c .rp__d { margin: 4px }
```
```html
<div class="cow">
  <div class="moo"></div>
</div>
```
```html
<div class="rp__display__--COLONblock rp__padding__--COLON10px rp__margin__--COLON4px_---PARENT1">
  <div class="rp__margin__--COLON4px_---CHILD"></div>
</div>
```
```html
<div class="rp__a rp__b rp__c">
  <div class="rp__d"></div>
</div>
```

This is gonna be a tough one
