### ISSUE TITLE
Allow setting the uglification index

### ISSUE THREAD

**Issue by TheJaredWilcurt** [red-perfume/red-perfume#20]
API to set the starting uglification index value. Probably in base 36

```js
  uglifierStartingIndex: 'a10d'
```
```css
.rp__a10d { padding: 1px }
.rp__a10e { margin: 20px }
.rp__a10f { background: #F00 }
```
