### ISSUE TITLE
Handle identical duplicate properties

### ISSUE THREAD

**Issue by TheJaredWilcurt** [red-perfume/red-perfume#48]
This:
```css
.example { 
  display: none;
  display: block;
  border: 1px solid #000;
  display: none;
}
```
should become
```js
.example {
  display: block;
  border: 1px solid #000;
  display: none;
}
```
In the classmap array, used by JSON and HTML

```js
Array.from(new Set(group.reverse())).reverse()
```
