### ISSUE TITLE
Uglify classnames

### ISSUE THREAD

**Issue by TheJaredWilcurt** [red-perfume/red-perfume#5]
```css
.rp__font-size__--COLON12px {font-size:12px}
.rp__background__--COLON__--OCTOTHORPF00 {background:#F00}
.rp__padding__--COLON8px {padding:8px}
...
.rp__z-index__--COLON999 {z-index:999}
```

```css
.rp__a {font-size:12px}
.rp__b {background:#F00}
.rp__c {padding:8px}
...
.rp_bhz9 {z-index:999}
```

Uglification would retain the prefix but numerically increment using an (a-z,0-9) Base 36 counting system.

Need to check if `.rp__ad` is detected by adblockers. It would not be uncommon to make it to 373 atomic classes (`373` is `ad` in Base 36).

```js
let uglifierIndex = 0;

function incrementUglifier () {
  uglifierIndex = uglifierIndex + 1;
  let knownBad = [
     'ad' // adblockers may hide these elements
  ];
  function containsBad (value) {
    return uglifierIndex.toString(36).includes(value);
  }
  while(knownBad.some(containsBad)) {
    uglifierIndex = uglifierIndex + 1;
  }
}

// ...
incrementUglifier();
'.rp__' + uglifierIndex.toString(36);
// something like that
```
